# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects quota Ansible role.
#
# The Webarchitects quota Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects quota Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects quota Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Quota role skipped
  ansible.builtin.debug:
    msg: "The tasks in the Quota role are not being run since the quota variable is not true."
  when: not quota | bool
  tags:
    - quota

- name: Run the tasks in this role
  block:

    - name: This role has only been tested on Debian  # noqa jinja[spacing]
      ansible.builtin.assert:
        that:
          - ansible_facts.distribution is defined
          - ansible_facts.distribution == "Debian"
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
        fail_msg: >-
          {%- if ansible_facts.distribution is defined -%}
          The {{ inventory_hostname }} server appears to be running {{ ansible_facts.distribution }} however this roles only supports Debian.
          {%- else -%}
          The variable ansible_facts.distribution_release is not defined for {{ inventory_hostname }}, please enable fact garthering.
          {%- endif -%}

    - name: Disable and remove quota
      ansible.builtin.include_tasks: absent.yml
      when:
        - quota | bool
        - quota_state == "absent"

    - name: Install, enable and configure quota
      ansible.builtin.include_tasks: enabled.yml
      when:
        - quota | bool
        - quota_state == "enabled"

  tags:
    - quota
...
