# Copyright 2019-2024 Chris Croome
#
# This file is part of the Webarchitects quota Ansible role.
#
# The Webarchitects quota Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects quota Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects quota Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Include quota requirements
  ansible.builtin.include_tasks: requirements.yml
  tags:
    - quota
    - quota_req

- name: Include quota local fact tasks
  ansible.builtin.include_tasks: local_facts.yml
  tags:
    - quota
    - quota_local_facts
    - quota_req

- name: Include quota check tasks
  ansible.builtin.include_tasks: checks.yml
  when: (quota is defined) and (quota | bool)
  tags:
    - quota
    - quota_check

- name: Configure quota tasks
  block:

    - name: Include journaled tasks for Debian Bullseye
      ansible.builtin.include_tasks: journaled.yml
      when: ansible_distribution_major_version is version('11', '>=')

    - name: Include aquota tasks for Debian Buster and Stretch
      ansible.builtin.include_tasks: aquota.yml
      when: ansible_distribution_major_version is version('11', '<')

  when: (quota is defined) and (quota | bool)
  tags:
    - quota
...
